'use strict'

module.exports = {
  NODE_ENV_PROD: 'production',
  NODE_ENV_DEV: 'development',
  DEV_APP_HOST_DEFAULT: 'localhost',
  DEV_APP_PORT_DEFAULT: 3055,
  DEV_SALT_ROUNDS_DEFAULT: 10,
  DEV_ACCESS_TOKEN_EXPIRES_DEFAULT: '1d',
  DEV_REFRESH_TOKEN_EXPIRES_DEFAULT: '90d',
  DEV_COOKIE_AT_MAX_AGE_DEFAULT: 1000 * 60 * 60 * 24 * 1, // 1 days
  DEV_COOKIE_RT_MAX_AGE_DEFAULT: 1000 * 60 * 60 * 24 * 90, // 90 days
  DEV_DB_HOST_DEFAULT: 'localhost',
  DEV_DB_PORT_DEFAULT: '3306',
  DEV_DB_NAME_DEFAULT: 'DEVELOPMENT_DATABASE',
  DEV_DB_USERNAME_DEFAULT: 'root',
  DEV_DB_PASSWORD_DEFAULT: '123456',
  PROD_APP_HOST_DEFAULT: 'localhost',
  PROD_APP_PORT_DEFAULT: 3055,
  PROD_SALT_ROUNDS_DEFAULT: 10,
  PROD_ACCESS_TOKEN_EXPIRES_DEFAULT: '1h',
  PROD_REFRESH_TOKEN_EXPIRES_DEFAULT: '90d',
  PROD_COOKIE_AT_MAX_AGE_DEFAULT: 1000 * 60 * 60 * 24 * 1, // 1 days
  PROD_COOKIE_RT_MAX_AGE_DEFAULT: 1000 * 60 * 60 * 24 * 90, // 90 days
  PROD_DB_HOST_DEFAULT: 'localhost',
  PROD_DB_PORT_DEFAULT: '3306',
  PROD_DB_NAME_DEFAULT: 'PRODUCTION_DATABASE',
  PROD_DB_USERNAME_DEFAULT: 'root',
  PROD_DB_PASSWORD_DEFAULT: '123456',
  REQUEST_HEADER_KEYS: {
    apiVersion: 'x-api-version',
    userId: 'x-user-id'
  },
  WHITELIST_DOMAINS: []
}