'use strict'

require('dotenv').config()

const {
  NODE_ENV_DEV,
  DEV_APP_HOST_DEFAULT,
  DEV_APP_PORT_DEFAULT,
  DEV_ACCESS_TOKEN_EXPIRES_DEFAULT,
  DEV_REFRESH_TOKEN_EXPIRES_DEFAULT,
  DEV_DB_HOST_DEFAULT,
  DEV_DB_PORT_DEFAULT,
  DEV_DB_NAME_DEFAULT,
  DEV_DB_USERNAME_DEFAULT,
  DEV_DB_PASSWORD_DEFAULT,
  PROD_APP_HOST_DEFAULT,
  PROD_APP_PORT_DEFAULT,
  PROD_ACCESS_TOKEN_EXPIRES_DEFAULT,
  PROD_REFRESH_TOKEN_EXPIRES_DEFAULT,
  PROD_DB_HOST_DEFAULT,
  PROD_DB_PORT_DEFAULT,
  PROD_DB_NAME_DEFAULT,
  PROD_DB_USERNAME_DEFAULT,
  PROD_DB_PASSWORD_DEFAULT
} = require('./constants.config')

const {
  NODE_ENV,
  APP_HOST,
  APP_PORT,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_DATABASE_NAME,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES
} = process.env

const development = {
  nodeEnv: NODE_ENV,
  app: {
    host: APP_HOST || DEV_APP_HOST_DEFAULT,
    port: APP_PORT || DEV_APP_PORT_DEFAULT,
    accessTokenExpires: ACCESS_TOKEN_EXPIRES || DEV_ACCESS_TOKEN_EXPIRES_DEFAULT,
    refreshTokenExpires: REFRESH_TOKEN_EXPIRES || DEV_REFRESH_TOKEN_EXPIRES_DEFAULT
  },
  mysql: {
    host: MYSQL_HOST || DEV_DB_HOST_DEFAULT,
    port: MYSQL_PORT || DEV_DB_PORT_DEFAULT,
    databaseName: MYSQL_DATABASE_NAME || DEV_DB_NAME_DEFAULT,
    username: MYSQL_USERNAME || DEV_DB_USERNAME_DEFAULT,
    password: MYSQL_PASSWORD || DEV_DB_PASSWORD_DEFAULT
  }
}

const production = {
  nodeEnv: NODE_ENV,
  app: {
    host: APP_HOST || PROD_APP_HOST_DEFAULT,
    port: APP_PORT || PROD_APP_PORT_DEFAULT,
    accessTokenExpires: ACCESS_TOKEN_EXPIRES || PROD_ACCESS_TOKEN_EXPIRES_DEFAULT,
    refreshTokenExpires: REFRESH_TOKEN_EXPIRES || PROD_REFRESH_TOKEN_EXPIRES_DEFAULT
  },
  mysql: {
    host: MYSQL_HOST || PROD_DB_HOST_DEFAULT,
    port: MYSQL_PORT || PROD_DB_PORT_DEFAULT,
    databaseName: MYSQL_DATABASE_NAME || PROD_DB_NAME_DEFAULT,
    username: MYSQL_USERNAME || PROD_DB_USERNAME_DEFAULT,
    password: MYSQL_PASSWORD || PROD_DB_PASSWORD_DEFAULT
  }
}

const envConfigs = {
  development,
  production
}

const envConfig = envConfigs[NODE_ENV] || envConfigs[NODE_ENV_DEV]

module.exports = envConfig